# Generated by Django 4.2.5 on 2023-10-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbi_recipe_appplication', '0002_ingredient_recipe_recipeingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepIndex', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('urlImg', models.CharField(max_length=255)),
                ('urlVideo', models.CharField(max_length=255)),
                ('ingredientsUsed', models.ManyToManyField(blank=True, to='cbi_recipe_appplication.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.ManyToManyField(blank=True, to='cbi_recipe_appplication.instruction'),
        ),
    ]
