# Generated by Django 4.2.5 on 2023-10-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbi_recipe_appplication', '0003_instruction_recipe_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbi_recipe_appplication.recipecategory'),
        ),
    ]
