# Generated by Django 4.2.5 on 2023-10-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbi_recipe_appplication', '0004_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
