# Generated by Django 4.2.5 on 2023-10-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbi_recipe_appplication', '0005_instruction_name_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='urlTeaserVideo',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='urlImg',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='ingredientsUsed',
            field=models.ManyToManyField(to='cbi_recipe_appplication.ingredient'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='urlImg',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='urlVideo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.ManyToManyField(to='cbi_recipe_appplication.instruction'),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='urlImg',
            field=models.CharField(max_length=1000),
        ),
    ]
