# Generated by Django 4.2.5 on 2023-10-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbi_recipe_appplication', '0006_recipe_servings_recipe_urlteaservideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.ManyToManyField(default=None, null=True, to='cbi_recipe_appplication.instruction'),
        ),
    ]
