# Generated by Django 4.2.5 on 2023-10-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbi_recipe_appplication', '0009_recipe_urlimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='isVegan',
            field=models.BooleanField(default=False),
        ),
    ]
